"""Playwright browser lifecycle and authorized download primitives."""

from .pdf_preferences import (
    PDF_DIRECT_DOWNLOAD_PREFERENCE,
    PdfPreferenceAudit,
    ResearchChromePdfPreference,
    ResearchChromePreferenceError,
    ResearchChromeProfileInUse,
)

from .manual_download_handoff import (
    ManualDownloadCandidateAmbiguous,
    ManualDownloadCandidateRejected,
    ManualDownloadDetection,
    ManualDownloadHandoff,
    ManualDownloadHandoffError,
    ManualDownloadHandoffResult,
    ManualDownloadHandoffState,
    ManualDownloadHandoffTimeout,
)
from .transport import BrowserPage, BrowserTransport, BrowserTransportError, validate_browser_transport
from .commands import (
    AuthenticatedFetchCommand,
    AuthenticatedFetchFailure,
    AuthenticatedFetchResult,
    BrowserActionResult,
    BrowserCommand,
    BrowserCommandError,
    BrowserCommandResult,
    BrowserObservation,
    BrowserPageSummary,
    BrowserTarget,
    BrowserTargetObservation,
    ClickCommand,
    DownloadArtifact,
    DownloadCaptureSpec,
    DownloadCommand,
    DownloadFailure,
    InvalidTarget,
    NavigateCommand,
    ObservationUnavailable,
    ObserveCommand,
    PageHandle,
    SessionHandle,
    UnsupportedCommand,
)
from .local_executor import LocalPlaywrightExecutor
from .port import BrowserCommandPort, ensure_browser_command_port, validate_browser_command_port

__all__ = [
    "PDF_DIRECT_DOWNLOAD_PREFERENCE",
    "PdfPreferenceAudit",
    "ResearchChromePdfPreference",
    "ResearchChromePreferenceError",
    "ResearchChromeProfileInUse",
    "ManualDownloadCandidateAmbiguous",
    "ManualDownloadCandidateRejected",
    "ManualDownloadDetection",
    "ManualDownloadHandoff",
    "ManualDownloadHandoffError",
    "ManualDownloadHandoffResult",
    "ManualDownloadHandoffState",
    "ManualDownloadHandoffTimeout",
    "BrowserPage",
    "BrowserTransport",
    "BrowserTransportError",
    "validate_browser_transport",
    "AuthenticatedFetchCommand",
    "AuthenticatedFetchFailure",
    "AuthenticatedFetchResult",
    "BrowserActionResult",
    "BrowserCommand",
    "BrowserCommandError",
    "BrowserCommandResult",
    "BrowserCommandPort",
    "BrowserObservation",
    "BrowserPageSummary",
    "BrowserTarget",
    "BrowserTargetObservation",
    "ClickCommand",
    "DownloadArtifact",
    "DownloadCaptureSpec",
    "DownloadCommand",
    "DownloadFailure",
    "InvalidTarget",
    "LocalPlaywrightExecutor",
    "NavigateCommand",
    "ObservationUnavailable",
    "ObserveCommand",
    "PageHandle",
    "SessionHandle",
    "UnsupportedCommand",
    "ensure_browser_command_port",
    "validate_browser_command_port",
]
